insert into author (id, name, first_name, last_name, affiliation_id) values (-1,'name1','first1','last1',-1);
insert into author (id, name, first_name, last_name, affiliation_id) values (-2,'name2','first2','last2',-2);
insert into author (id, name, first_name, last_name, affiliation_id) values (-3,'name3','first3','last3',-3);
insert into author_page_rank (author_id, page_rank) values (-1,0.33);
insert into author_page_rank (author_id, page_rank) values (-2,0.13);
insert into author_page_rank (author_id, page_rank) values (-3,0.43);
insert into affiliation (id, name) values (-1,'aff1');
insert into affiliation (id, name) values (-2,'aff2');
insert into affiliation (id, name) values (-3,'aff3');
insert into user value (4, 'testset1', '123456', '管理员');