spring:
  profiles:
    active: "@profileActive@"
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.dwxh.xyz:3306/IIICEStseB?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: IIICEStseB
  jackson:
    time-zone: GMT+8

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      max-file-size:
        104857600
      max-request-size:
        104857600


mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  tomcat:
    uri-encoding: utf-8
  port: 4000


---
spring:
  profiles: prod
  devtools:
    add-properties: false
logging:
  level:
    root: info
server:
  port: 4000
---
spring:
  profiles: dev
  devtools:
    add-properties: true
  datasource:
    username: root
logging:
  level:
    group.iiicestseb.backend: DEBUG
server:
  port: 4001
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: test
  devtools:
    add-properties: true
  datasource:
    username: root
logging:
  level:
    group.iiicestseb.backend: DEBUG
server:
  port: 4001
management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: test
  devtools:
    add-properties: true
  datasource:
    username: root
    password: IIICEStseB
logging:
  level:
    group.iiicestseb.backend: DEBUG
server:
  port: 4001
management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: dwh
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/IIICEStseB?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      max-lifetime: 3600000
  devtools:
    add-properties: true
server:
  servlet:
    session:
      timeout: 7200
logging:
  level:
    group:
      iiicestseb:
        backend: DEBUG
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: jh
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/IIICEStseB?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      max-lifetime: 3600000
  devtools:
    add-properties: true
server:
  servlet:
    session:
      timeout: 7200
logging:
  level:
    group:
      iiicestseb:
        backend:
          DEBUG
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: wph
  datasource:
    password: shengdasogood
    url: jdbc:mysql://localhost:3306/iiicestseb?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      max-lifetime: 3600000
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    add-properties: true

server:
  servlet:
    session:
      timeout: 7200
logging:
  level:
    group:
      iiicestseb:
        backend:
          DEBUG
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: lwj
  datasource:
    username: root
    password:  LWJsteve98
    url: jdbc:mysql://localhost:3306/IIICEStseB?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      max-lifetime: 3600000
  devtools:
    add-properties: true
server:
  servlet:
    session:
      timeout: 7200
logging:
  level:
    group:
      iiicestseb:
        backend:
          DEBUG
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: local
  devtools:
    add-properties: true
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/IIICEStseB?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: iii
    password: iii
  jackson:
    time-zone: GMT+8
logging:
  level:
    group.iiicestseb.backend: DEBUG
server:
  port: 4002
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
